<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>com.example.avro</groupId>
    <artifactId>avro-rest-service</artifactId>
    <version>0.0.2-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>avro-rest-service</name>
    <description>Simple Spring Boot REST service using Avro payloads</description>
    <modules>
        <module>avro-model</module>
        <module>sim-engine-backend</module>
        <module>large-payload-webflux</module>
        <module>calculation-engine</module>
        <module>simulation-engine</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <avro.version>1.11.3</avro.version>
    </properties>

</project>
