{
  "type": "record",
  "name": "TrafficLogEvent",
  "namespace": "com.example.avro.model",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "eventTime",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "serviceName",
      "type": "string"
    },
    {
      "name": "httpMethod",
      "type": "string"
    },
    {
      "name": "path",
      "type": "string"
    },
    {
      "name": "statusCode",
      "type": "int"
    },
    {
      "name": "durationMs",
      "type": "long"
    },
    {
      "name": "correlationId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "requestId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "clientIp",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "userAgent",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "systemId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "metadata",
      "type": {
        "type": "map",
        "values": "string"
      },
      "default": {}
    }
  ]
}

