server.port=8082
spring.application.name=sim-engine-backend
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
app.kafka.logging-topic=logging-test-topic
app.kafka.logging-enabled=true

